site_name: LH_ED_Rafael07 - Data Engineering Challenge
site_description: Code challenge for Software Developer with focus in data projects - Indicium
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - Home: index.md
  - Arquitetura:
    - Visão Geral: architecture/overview.md
    - Fluxo de Dados: architecture/data_flow.md
    - Tecnologias: architecture/technologies.md
  - Implementação:
    - Step 1 - Extração: implementation/step1_extraction.md
    - Step 2 - Carregamento: implementation/step2_loading.md
    - DAGs Airflow: implementation/airflow_dags.md
  - Setup:
    - Requisitos: setup/requirements.md
    - Instalação: setup/installation.md
    - Configuração: setup/configuration.md
  - Operação:
    - Execução: operations/execution.md
    - Monitoramento: operations/monitoring.md
    - Troubleshooting: operations/troubleshooting.md