[project]
name = "airflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.7"
dependencies = [
    "apache-airflow>=2.10.4",
    "apache-airflow-providers-celery>=3.10.0",
    "pandas>=2.2.3",
    "pendulum>=3.0.0",
]
